/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenlab10p2_heydenalfonsoaldanavarela_22111098;

import java.io.FileInputStream;
import java.io.InputStream;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author heyde
 */
public class jfLose extends javax.swing.JFrame {

    /**
     * Creates new form jfLose
     */
    public jfLose() {
        initComponents();
        try
        {
            tocar();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void tocar() throws Exception
    {
        String sonido = "./src/examenlab10p2_heydenalfonsoaldanavarela_22111098/musical.wav";
        InputStream io = new FileInputStream(sonido);
        InputStream audio = new AudioStream(io);
        AudioPlayer.player.start(audio);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bcontinuar = new javax.swing.JButton();
        bsalirjuego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examenlab10p2_heydenalfonsoaldanavarela_22111098/santatriste.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 220, 260));

        jLabel2.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText(" H A   P E R D I D O");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        bcontinuar.setBackground(new java.awt.Color(153, 0, 0));
        bcontinuar.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        bcontinuar.setForeground(new java.awt.Color(255, 102, 102));
        bcontinuar.setText("c o n t i n u a r");
        bcontinuar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bcontinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bcontinuarMouseClicked(evt);
            }
        });
        jPanel1.add(bcontinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 210, 60));

        bsalirjuego.setBackground(new java.awt.Color(153, 0, 0));
        bsalirjuego.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        bsalirjuego.setForeground(new java.awt.Color(255, 102, 102));
        bsalirjuego.setText("s a l i r");
        bsalirjuego.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bsalirjuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsalirjuegoMouseClicked(evt);
            }
        });
        jPanel1.add(bsalirjuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 210, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bcontinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcontinuarMouseClicked
        jJuego h = new jJuego();
        h.setVisible(true);
        this.hide();
    }//GEN-LAST:event_bcontinuarMouseClicked

    private void bsalirjuegoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsalirjuegoMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bsalirjuegoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfLose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfLose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfLose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfLose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfLose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcontinuar;
    private javax.swing.JButton bsalirjuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
